version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      emotion:
        patterns:
          - "@emotion/*"
      react:
        patterns:
          - "react"
          - "react-dom"
      eslint:
        patterns:
          - "*eslint*"
      nivo:
        patterns:
          - "@nivo/*"
