name: update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * SAT"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: update data
        run: ./do update-data
      - name: create PR
        run: |
          if git diff-index --quiet HEAD --; then
            exit 0;
          fi

          git checkout -b update-data
          git config --global user.name 'Jan Sepke'
          git config --global user.email '625043+jansepke@users.anoreply.github.com'
          git commit -am "update data"
          git push -u origin update-data:update-data
          pr_url=$(gh pr create --title 'update data' --body 'Created by Github action')
          echo "$pr_url"
          gh pr merge --auto --rebase "$pr_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
